# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-18.04"

# Install Python3, Python3-pip on VirtualBox via vagrant

  config.vm.provision "shell", path: "bootstrap.sh", privileged: false

# Copy file from host to guest via vagrant

  config.vm.provision "file", source: "test.txt", destination: "/home/vagrant/test.txt"
     
end
